apiVersion: v1
kind: Pod
metadata:
  name: ssh-pod
spec:
  containers:
  - name: ssh-pod
    image: nginx
    lifecycle:
      postStart:
        exec:
          command: ["/bin/bash", "-c", "apt-get update && apt-get install openssh-client vim sshpass -y"]
  nodeSelector:
    "kubernetes.io/os": linux
